"""Domain contracts shared across API, database, and service layers."""

from src.domain.contracts import (
    CurrentPlayerStatsRecord,
    FixtureRecord,
    GameweekHistoryRecord,
    PlayerRecord,
    Position,
    RecommendationScoreRecord,
    TeamRecord,
)
from src.domain.schedule_risk import (
    AuditableProbabilityInput,
    CandidateRescheduleSlot,
    CompetitionCode,
    CompetitionEvent,
    CompetitionStage,
    FixtureRiskScenario,
    FixtureProbabilityProjection,
    FractionalOddsOutcome,
    GameweekRiskSummary,
    DoubleGameweekProbabilityProjection,
    LicensedOddsMarket,
    NormalizedOddsProbability,
    ParticipationStatus,
    ProbabilityConfidence,
    ProbabilityTargetType,
    ProjectionMethod,
    ScenarioOutcome,
    ScheduleRiskStatus,
    StructuralFixtureClash,
    TeamCompetitionEntry,
)

__all__ = [
    "CurrentPlayerStatsRecord",
    "FixtureRecord",
    "GameweekHistoryRecord",
    "PlayerRecord",
    "Position",
    "RecommendationScoreRecord",
    "TeamRecord",
    "AuditableProbabilityInput",
    "CandidateRescheduleSlot",
    "CompetitionCode",
    "CompetitionEvent",
    "CompetitionStage",
    "FixtureRiskScenario",
    "FixtureProbabilityProjection",
    "FractionalOddsOutcome",
    "GameweekRiskSummary",
    "DoubleGameweekProbabilityProjection",
    "LicensedOddsMarket",
    "NormalizedOddsProbability",
    "ParticipationStatus",
    "ProbabilityConfidence",
    "ProbabilityTargetType",
    "ProjectionMethod",
    "ScenarioOutcome",
    "ScheduleRiskStatus",
    "StructuralFixtureClash",
    "TeamCompetitionEntry",
]
